### ISSUE TITLE
[BUG?] Lethal Company seems to be unable to finish after taking off with this mod enabled?

### ISSUE THREAD

**Issue by LunarstarFurry** [EliteMasterEric/CevaScrapRebalance#2]
So I'm not really sure why but every time when I have this mod enabled, the ship always seems to just get stuck right after taking off from any planet with this error printed on BepInEx?  Any idea what could be causing this?

`[Info   : Unity Log] Despawning props and enemies #2
[Info   : Unity Log] Despawning props and enemies #3
[Info   : Unity Log] Enemies on map: 1
[Info   : Unity Log] despawn enemies on map
[Info   :Starlancer AI Fix] Centipede(Clone) from the interior enemy list has died;
Previous interior power level is 0
[Info   :Starlancer AI Fix] Removing Centipede(Clone)'s power (1) from the RoundManager;
Current interior power level is 0
[Warning: Unity Log] [Netcode] NetworkObject #187 moved to the root because its parent NetworkObject #182 is destroyed
[Warning: Unity Log] [Netcode] NetworkObject #188 moved to the root because its parent NetworkObject #186 is destroyed
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCOffice.Patches.StartOfRoundPatch.SceneManager_OnUnloadComplete_Prefix () (at <c58f7d31c0a940bfbc47d1baab6fc0db>:IL_0006)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SceneManager_OnUnloadComplete>(StartOfRound,ulong,string)
Unity.Netcode.NetworkSceneManager.OnSceneUnloaded (System.UInt32 sceneEventId) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0149)
Unity.Netcode.SceneEventProgress.<SetAsyncOperation>b__37_0 (UnityEngine.AsyncOperation asyncOp2) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0012)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at <e27997765c1848b09d8073e5d642717a>:IL_000F)
`

**Comment by EliteMasterEric** [comment]
This seems like an issue with another mod, whatever `LCOffice` is.

**Comment by LunarstarFurry** [comment]
Hmmm I'll try to disable it maybe a conflict?

**Comment by LunarstarFurry** [comment]
it does indeed seems to be a conflict between LC_Office and Rebalance Thankyou! Not sure why tho sicne Office adds interior.
